[option]
exclude_paths = []

[rules]
case_default = true
enum_with_type = false
for_with_begin = false
function_same_as_system_function = false
function_with_automatic = false
generate_for_with_label = false
generate_if_with_label = false
generate_keyword = false
genvar_declaration = false
if_with_begin = true
inout_with_tri = false
input_with_var = false
legacy_always = true
level_sensitive_always = false
loop_variable_declaration = false
non_ansi_module = true
output_with_var = false
parameter_in_package = false
priority_keyword = true
tab_charactor = true
unique0_keyword = false
unique_keyword = false
wire_reg = true
#syntaxrules.blocking_assignment_in_always_ff = true
#syntaxrules.non_blocking_assignment_in_always_comb = true
#syntaxrules.enum_with_type = true
#syntaxrules.keyword_forbidden_priority = true
#syntaxrules.keyword_forbidden_unique = true
#syntaxrules.keyword_forbidden_unique0 = true
#syntaxrules.procedural_continuous_assignment = true
#syntaxrules.action_block_with_side_effect = true
#syntaxrules.default_nettype_none = true
#syntaxrules.function_same_as_system_function = true
#syntaxrules.keyword_forbidden_wire_reg = true
#syntaxrules.module_nonansi_forbidden = true
#syntaxrules.localparam_type_twostate = true
#syntaxrules.parameter_type_twostate = true
#syntaxrules.localparam_explicit_type = true
#syntaxrules.parameter_explicit_type = true
#syntaxrules.parameter_default_value = true
#syntaxrules.parameter_in_generate = true
#syntaxrules.parameter_in_package = true
#syntaxrules.genvar_declaration_in_loop = true
#syntaxrules.genvar_declaration_out_loop = false
#syntaxrules.keyword_forbidden_generate = true
#syntaxrules.keyword_required_generate = false
#syntaxrules.multiline_for_begin = true
#syntaxrules.multiline_if_begin = true
#syntaxrules.inout_with_tri = true
#syntaxrules.input_with_var = true
#syntaxrules.output_with_var = true
#syntaxrules.interface_port_with_modport = true
